[phases.install]
cmds = [
  "npm i -g corepack@latest && corepack enable && corepack prepare --activate",
  "pnpm install --no-frozen-lockfile --prefer-offline"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "node dist/index.js"
